version: '3.9'

services:
  backend:
    build: ./backend
    container_name: ezlife-backend
    ports:
      - "8000:8000"
    volumes:
      - ./backend:/app
    environment:
      - MONGO_URI=mongodb+srv://ezlifedb:ezlifepassword@ezlife.tyhljcz.mongodb.net/?retryWrites=true&w=majority&appName=EZlife
      - HF_TOKEN=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

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: ezlife-frontend
    ports:
      - "5173:80" # Frontend is served via Nginx on port 80 inside the container
    depends_on:
      - backend

  user-service:
    build: ./backend/user-service
    container_name: user-service
    ports:
      - "8001:8001"
    environment:
      - MONGO_URI=mongodb+srv://ezlifedb:ezlifepassword@ezlife.tyhljcz.mongodb.net/?retryWrites=true&w=majority&appName=EZlife
