services:
  backend:
    build: ./backend
    container_name: ezlife-backend
    ports:
      - "8000:8000"
    volumes:
      - ./backend:/app
    env_file:
      - ./backend/.env
    environment:
      - TASK_ESTIMATION_SERVICE_URL=http://task-estimation-service:8002 # it's needed for the API calls (openrouter's requests format)

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: ezlife-frontend
    ports:
      - "5173:80" 
    depends_on:
      - backend

  user-service:
    build:
      context: ./backend
      dockerfile: user-service/Dockerfile 
    container_name: user-service
    ports:
      - "8001:8001"
    env_file:
      - ./backend/.env

  task-estimation-service:
    build: ./backend/task-estimation-service
    container_name: task-estimation-service
    ports:
      - "8002:8002"
    env_file:
      - ./backend/.env
    volumes:
      - ./backend/task-estimation-service:/app 

  file-service:
    build:
      context: ./backend/file-service
      dockerfile: Dockerfile
    container_name: file-service
    ports:
      - "8003:8003"
    env_file:
      - ./backend/.env
    volumes:
      - ./backend/file-service:/app
      - file_uploads:/app/uploads



volumes:
  file_uploads:
    driver: local
